global-business-support/evalvue-frontend

src/Components/Navbar.jsx
src/Components/Registration.jsx
src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/SearchOutlet.jsx
src/Pages/Dashboard/SubServices.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Enpreviewoutlet.jsx
src/Pages/Footer.jsx
src/Pages/Landing.jsx
src/Pages/Personalreview.jsx
src/main.jsx

Commiting Aadhar and Organization Changes

Commiting Aadhar and Organization Changes

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Organization.jsx

Verification

---

src/Components/Navbar.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Passwordgenrate.jsx
tailwind.config.js

navbar fix

---

src/Components/Loginfile.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/ThreeDotMenu.jsx

three dot menu

---

src/Components/Registration.jsx
src/Pages/Dashboard/Organization.jsx

pending org ande view button

---

src/Pages/Dashboard/Addorganization.jsx

loader resolve

---

src/Components/Navbar.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx

feed card issue resolve

---

src/Components/Navbar.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/ThreeDotMenu.jsx
src/Pages/Dashboard/Viewemp.jsx

Edit Employee Option Added

---

src/Components/Registration.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Enpreviewoutlet.jsx
src/Pages/Footer.jsx
src/Pages/Help.jsx
src/Pages/Landing.jsx

resolve responsiveness issue

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Organization.jsx

conflict resolve

---

src/Components/Navbar.jsx
src/Pages/Contact.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/ScrollTotop.jsx
src/Pages/Dashboard/Services.jsx
src/Pages/Enpreviewoutlet.jsx
src/main.jsx

button functionality added

---

src/Components/Loginfile.jsx
src/Pages/Apibackendrequest.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Personalreview.jsx

Login api update

---

src/Pages/Dashboard/Post.jsx

make rating compulsory and add image uploader in review

make rating compulsory and add image uploader in review

---

src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Enpreviewoutlet.jsx

update organization header

---

src/Pages/Contact.jsx
src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Services.jsx
src/Pages/Landing.jsx

org bug resolved

---

src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Personalreview.jsx

Adhar card update

---

src/Components/Loginfile.jsx
src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Viewemp.jsx

API Managemnt

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Parentcomponent.jsx
src/Pages/Personalreview.jsx

api management by aman

---

src/Components/Loginfile.jsx
src/Components/Navbar.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Enpreviewoutlet.jsx
src/Pages/Passwordotp.jsx

ui bug fixed

---

src/Components/Navbar.jsx
src/Contextfile.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Viewemp.jsx

view employee org name issue resolved

view employee org name issue resolved

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Parentcomponent.jsx

login page bug resolved

---

src/Components/Navbar.jsx
src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Personalreview.jsx

Image added in feed

---

src/Pages/Dashboard/DashboardHome.jsx
src/Pages/Dashboard/Post.jsx

add image in post

---

src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/ThreeDotMenu.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Enpreviewoutlet.jsx

employee list UI fixed

---

src/Pages/Apibackendrequest.jsx

token api checked

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Passwordgenrate.jsx

terminate button added in search by aadhaar

terminate button added in search by aadhaar

---

src/Components/Loginfile.jsx
src/Components/LogoutButton.jsx
src/Components/Navbar.jsx
src/Pages/Apibackendrequest.jsx
src/Pages/Dashboard/apiClient.js

add interceptors

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/apiClient.js
src/Pages/Personalreview.jsx

Add header in intercepter

---

.env
src/Pages/Dashboard/Addorganization.jsx

production , add referral

---

src/Components/Loginfile.jsx

login error handled

---

src/Pages/Dashboard/Addorganization.jsx

update referrel code

---

src/AdminPanel/OrgDetails.jsx

Orgainzation page for admin added

Orgainzation page for admin added

---

src/AdminPanel/OrgDetails.jsx
src/Pages/Dashboard/Post.jsx

review image delete update

---

src/Pages/Passwordotp.jsx

otp timer, cut option, loader added

otp timer, cut option, loader added

---

src/Components/Loginfile.jsx
src/Contextfile.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/ProtectedAadhaarRoute.jsx
src/main.jsx

search by Aadhaar conditionaly rendered

search by Aadhaar conditionaly rendered

---

src/Pages/Dashboard/DashboardNavigation.jsx

search by Aadhar conditionaly rendered on desktop devices

search by Aadhar conditionaly rendered on desktop devices

---

src/AdminPanel/OrgDetails.jsx
src/AdminPanel/VerifyOrganization.jsx
src/Pages/Landing.jsx

video and search bar added to home page and admin orgPage respectively

video and search bar added to home page and admin orgPage respectively

---

src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Empform.jsx

image validation and state problem solve

image validation and state problem solve

---

src/Pages/Dashboard/AddEmployee.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Passwordotp.jsx

shoot otp payload updated

---

src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Payment/Subscription.jsx
src/Payment/TransactionHistory.jsx
src/main.jsx

payement pages added

---

src/Pages/Dashboard/AddEmployee.jsx
src/Pages/Dashboard/Dashboard.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Orgoutlet.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Passwordotp.jsx

shoot otp and verify otp issue resolved

shoot otp and verify otp issue resolved

---

src/Components/Clock.jsx
src/Pages/Landing.jsx
src/main.jsx

clock component created

---

src/Components/Navbar.jsx
src/Components/UserDetails.jsx
src/Pages/Dashboard/AddEmployee.jsx

bug resolve

---

src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Orgoutlet.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx

navigate button removed from mobile view

navigate button removed from mobile view

---

src/Pages/About.jsx
src/Pages/Contact.jsx
src/Pages/Dashboard/Services.jsx
src/Pages/Dashboard/SubServices.jsx
src/Pages/Help.jsx
src/Pages/Landing.jsx

home,contact,services,help page alignment resolved

home,contact,services,help page alignment resolved

---

src/Pages/Enpreviewoutlet.jsx

in Emprereviewoutlet employee name text size fixed

in Emprereviewoutlet employee name text size fixed

---

src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Viewemp.jsx

refresh bug resolve

---

src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/Viewemp.jsx

design resolved

---

src/Components/Clock.jsx
src/Pages/Dashboard/AddEmployee.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Enpreviewoutlet.jsx
src/Pages/Personalreview.jsx

clock update

---

src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Personalreview.jsx

update aadhar function

---

src/Components/LogoutButton.jsx
src/Components/UserDetails.jsx
src/Pages/About.jsx
src/Pages/Contact.jsx
src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Help.jsx
src/Pages/Personalreview.jsx

UI resolution inhancement

---

src/Components/Clock.jsx
src/Pages/Dashboard/AddEmployee.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Passwordotp.jsx

forgot password and add terminated employee opt timer created

forgot password and add terminated employee opt timer created

---

src/Pages/Dashboard/AddEmployee.jsx

incorrect otp error handled

---

src/Components/Navbar.jsx
src/Pages/Dashboard/RejectOrg.jsx
src/Pages/Dashboard/ScrollTotop.jsx
src/main.jsx

reApply organization feature added

reApply organization feature added

---

.env
index.html
src/Pages/Dashboard/Organization.jsx

Payment intrigate

---

src/AdminPanel/VerifyOrganization.jsx
src/Pages/Dashboard/Organization.jsx

reject message field added in verify  organization

reject message field added in verify  organization

---

src/Pages/Dashboard/Organization.jsx

payment successfull

---

src/Pages/Dashboard/Organization.jsx

payment receipt added created

---

src/AdminPanel/VerifyOrganization.jsx
src/Payment/Subscription.jsx

subscription details showed in subscription table

subscription details showed in subscription table

---

src/AdminPanel/OrgDetails.jsx
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Empform.jsx
src/Pages/Dashboard/Post.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Payment/TransactionHistory.jsx

payment history page added

---

package-lock.json
package.json
src/Pages/Dashboard/Organization.jsx
src/index.css

add payment receipt

---

src/Payment/Subscription.jsx
src/Payment/TransactionHistory.jsx

payment history error resolved

payment history error resolved

---

src/AdminPanel/OrgDetails.jsx
src/Pages/Passwordotp.jsx

paid option added in admin panel

paid option added in admin panel

---

src/AdminPanel/VerifyOrganization.jsx
src/Payment/Subscription.jsx

error message correction in VerifyOrganization

error message correction in VerifyOrganization

---

src/Pages/Dashboard/Organization.jsx

payment receipt

---

src/Pages/Dashboard/Organization.jsx

remove receipt error

---

src/Pages/Dashboard/Organization.jsx

payment error resolve

---

.env

production payment

---

src/Pages/Passwordotp.jsx

update otp verification

---

.env
package-lock.json
src/Components/Swiperr.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Landing.jsx
src/Payment/Subscription.jsx

update landing page

---

src/Pages/Dashboard/DashboardNavigation.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/Orgoutlet.jsx
src/Pages/Dashboard/SearchByAadharCard.jsx
src/Pages/Dashboard/Viewemp.jsx
src/Pages/Enpreviewoutlet.jsx

fixed ui bugs

---

src/Components/Swiperr.jsx
src/Pages/Landing.jsx

home page review slider added

---

src/Payment/Subscription.jsx

subscription details table changes

subscription details table changes

---

.env
src/Pages/Dashboard/Organization.jsx
src/Pages/Footer.jsx

final production

---

.env
src/Pages/Dashboard/Organization.jsx

test changes

---

.env
src/Pages/Dashboard/Organization.jsx

changes production

---

.env
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Addorganization.jsx
src/Pages/Dashboard/Organization.jsx

update  add organization

---

.env
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Organization.jsx

update production add organization

Abhishek 3

---

.env
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Organization.jsx

update payment receipt pro

---

.env
index.html
package-lock.json
package.json
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Organization.jsx
src/Pages/Dashboard/ThreeDotMenu.jsx
src/Pages/Landing.jsx
src/Payment/Subscription.jsx
src/Payment/TransactionHistory.jsx
src/main.jsx

update seo config test

---

.env
src/AdminPanel/PrivateRoute.jsx
src/Pages/Dashboard/Organization.jsx

update seo prod
